# Generated by Django 4.1.1 on 2022-09-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiat', '0003_alter_document_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='percent',
            field=models.IntegerField(default=0),
        ),
    ]
